# ============================================================================
# mosquitto-ecdsa.conf — Mosquitto broker config for ECDSA baseline
# Runs on port 8885 (RSA is on 8884, PQC is on 8883)
# ============================================================================

per_listener_settings true
log_type all
log_dest stderr

listener 8885 0.0.0.0

cafile   ./pki/output/classical/ecdsa/ca.crt
certfile ./pki/output/classical/ecdsa/broker.crt
keyfile  ./pki/output/classical/ecdsa/broker.key

require_certificate true
use_identity_as_username true
tls_version tlsv1.3
